//Escreva um programa que solicita ao usuário um nome de usuário e uma senha. Verifique se o
//nome de usuário é &quot;admin&quot; e a senha é &quot;senha123&quot;. Exiba uma mensagem indicando se o login
//foi bem-sucedido ou não.


let nome = prompt ("Olá, digite seu nome")
let senha = prompt ("Olá, digite sua senha")
//Concatenação
console.log ("Seja bem vindo " + nome);




/*
// Pontos
let pontos = 100
let bonus = parseFloat (prompt ("Quantos pontos você deseja somar"))
//Concatenação
console.log (pontos + bonus)
*/

/*
let nota = parseFloat ( prompt("Digite a nota do aluno: "))
let bonus = parseFloat (prompt ("Quantos pontos você deseja somar"))
let pontuacaoTotal = nota + bonus
console.log ("A nota é " + pontuacaoTotal)
*/


/*
Adição -> num1 + num2
Subtraçaõ -> num1 - nums2
Multiplicação -> num1 * num2
Divisão -> num1 / num2
*/